### ISSUE TITLE
[FEATURE REQUEST] isn't there any ways to do Futures trades ?

### ISSUE THREAD

**Issue by Hassan-Fa** [nardew/cryptoxlib-aio#23]
sorry if this feature exists and I didn't find it , just point me in the right direction 🙏 

💕

**Comment by nardew** [comment]
Hi, not at the moment since there was no demand for it. Which exchange are you interested in?

**Comment by Hassan-Fa** [comment]
oh ok

I guess if there's any demand for Futures it'd be BTCUSDTPERP

**Comment by nardew** [comment]
Hi @Hassan-Fa, I am afraid that implementation of futures is not priority at the moment. It could be worked on in the future but I cannot give you any estimate. Sorry.

**Comment by Diadikos87** [comment]
Hi @nardew . Have you perhaps reconsidered this feature, for Binance at least?

**Comment by nardew** [comment]
Hi @Diadikos87, which endpoints are interested in in particular? Margin/futures endpoints from https://binance-docs.github.io/apidocs/spot/en/ will potentially be ready in the near future due to a help from community members. Endpoints for usds-m and coin-m futures are still not planned. If these are the endpoints you are after, then you can list here the calls which you are most interested in and I will see what I can do.

**Comment by xiandong79** [comment]
Thanks for your awesome work.

yeah, I agree that Binance Future, the largest trading platform is needed.

**Comment by nardew** [comment]
Hi @xiandong79 , same question as above, which endpoints are you interested in? Usds-m, coin-m, ... based on that I could prioritize them.

**Comment by xiandong79** [comment]
Usds-m for now. as the existing libs for Usds-m are all sync version.

**Comment by nardew** [comment]
@xiandong79 @Diadikos87 @Hassan-Fa the library now contains full implementation of USDS-M Futures. The changes are done on the PR #44 which can be cloned and used. Any feedback is welcome. Margin endpoints and COIN-M futures will come soon.

**Comment by nardew** [comment]
Margin endpoints added into the same PR thanks to @davidmcnabnz
