### ISSUE TITLE
the websocket and REST api for FTX

### ISSUE THREAD

**Issue by xiandong79** [nardew/cryptoxlib-aio#53]
the FTX exchange is real rising star in the crypto trading domain.

https://ftx.com/volume-monitor
![Screen Shot 2021-05-21 at 16 14 54](https://user-images.githubusercontent.com/22584737/119105251-b4986100-ba4f-11eb-9dba-a232b29af6ee.png)

**Comment by xiandong79** [comment]
yeah, the FTX deserve a place

**Comment by nardew** [comment]
Hi,
I totally agree that FTX has become a prominent exchange, no doubt about that. The problem is there is literally no demand among cryptoxlib users and given the richness of FTX's API it is therefore very unappealing for me to invest my free time into it. I hope you understand. Maybe if you list particular calls you are intetested in, then I can start with those when time permits.
