### ISSUE TITLE
test network

### ISSUE THREAD

**Issue by grahamers** [nardew/cryptoxlib-aio#70]
hi, 

crptoxlib is working nicely for me, however I need to switch over to binance testnet... as we're testing trading and obviously cant trade with real network during dev cycle. 

while I know this isn't strictly speaking the place to ask this but... 

we download historical trades from 

https://data.binance.vision/data/spot/daily/trades/

We then use

**binance_client.get_historical_trades(symbol_pair, 1000, last_trade_id)**

To get the trades since "last_trade_id" .. this works perfectly in prod, the IP address is setup so the client call is accepted. However using the demo keys, I get; 

 response [{'code': -2015, 'msg': 'Invalid API-key, IP, or permissions for action.'}]
 
 Not sure where/how I validate the test net new keys I have generated for test net (Im using newly generated keys instead of the old "production" ones). Again the documentation is a bit all over the place, I find. 

thanks much,

Graham

**Comment by nardew** [comment]
Hi @grahamers, testnet keys can be generated at `https://testnet.binance.vision`. First choose `Log In with GitHub` and then `Generate HMAC_SHA256 Key`. The generated API & SEC key have unlimited privileges. If you generated the keys this way and you are passing them to `create_binance_testnet_client` properly, then I unfortunately cannot really tell where the issue is but I do not think it is on the library side. You can paste the generate API and SEC key here (only for testnet!) and include your code and we can have a look.

**Comment by grahamers** [comment]
Ah thanks a million Nardew! I completely missed the fact that there was a create_binance_test_client method. My bad. 

Just so I'm not missing anything , I'm working off thisURL for documentation;

https://github.com/nardew/cryptoxlib-aio/tree/master/examples

I really like this library BTW! Nice work CrytoxLib! 

GrahamO
